server:
  port: 8080

bar:
  ribbon:
    listOfServers: localhost:8081


feign.client.config:
  bar:
    loggerLevel: full
    errorDecoder: com.example.fooservice.SimpleErrorDecoder
    requestInterceptors:
#    - com.example.fooservice.FooRequestInterceptor

logging:
  level:
    feign: trace


