server:
  port: 8080

bar-service:
  ribbon:
    listOfServers: localhost:8081

feign.client.config:
  bar-service:
    loggerLevel: full
    decode404: true
    requestInterceptors:
     - com.example.fooservice.FooRequestInterceptor

logging:
  level:
    com.example.fooservice.BarServiceClient: debug
