server:
  port: 8080

bar-service:
  ribbon:
    listOfServers: localhost:8081

feign.client.config:
  bar-service:
    loggerLevel: full
    #    errorDecoder: com.example.fooservice.SimpleErrorDecoder
    decoder: com.example.fooservice.SimpleDecoder
    decode404: true
    requestInterceptors:
     - com.example.fooservice.FooRequestInterceptor

logging:
  level:
    feign: trace

feign:
  client:
    config:
